name: "✨ Feature Request"
description: "Suggest a new idea or improvement"
title: "[Feature] "
labels: 
  - feature
assignees: 
  - Greedeks

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Briefly describe your idea and why it would be useful."
      placeholder: "I suggest adding..."
    validations:
      required: true