name: "✨ Feature Request"
description: "Suggest an idea for this project"
title: "[Feature Request] <Feature Title>"
labels: 
  - enhancement
  - experience using
assignees: 
  - Greedeks

body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: "Provide a detailed description of the feature. Describe what the feature should do, how it is expected to work, and include any relevant background or context that explains its importance."
      placeholder: "Describe your feature request in detail..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 Alternatives Considered"
      description: "Describe any alternative solutions or approaches you've evaluated, and explain why the proposed feature is preferred."
      placeholder: |
        - **Alternative 1:** Explain the alternative approach and its limitations.  
        - **Alternative 2:** Describe another possible solution and why it wasn't selected.  
        - **Alternative 3 (if applicable):** Mention any other options and the reasons for excluding them.
