name: "🐞 Bug Report"
description: "Description of the error or the problem with the utility"
title: "[BUG] Title"
labels:
  - bug
  - help wanted
  - wontfix
assignees:
  - Greedeks

body:
  - type: textarea
    id: problem_description
    attributes:
      label: "🚨 Problem Description"
      description: "Describe the nature of your problem. Or the conditions of its occurrence and attach screenshots or error logs if possible."
      placeholder: "Explain the issue in detail..."
    validations:
      required: true
