//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTweak.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTweak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Apps&gt;
        ///    &lt;App&gt;
        ///        &lt;Icon&gt;Img_Nvidia&lt;/Icon&gt;
        ///        &lt;Name&gt;NVIDIA App&lt;/Name&gt;
        ///        &lt;Group&gt;web&lt;/Group&gt;
        ///        &lt;Author&gt;(C) NVIDIA Corporation&lt;/Author&gt;
        ///        &lt;AuthorIcon&gt;nvidia.com&lt;/AuthorIcon&gt;
        ///        &lt;Source&gt;https://www.nvidia.com/en-eu/software/nvidia-app/&lt;/Source&gt;
        ///        &lt;DownloadPath&gt;https://www.nvidia.com/en-us/software/nvidia-app/&lt;/DownloadPath&gt;
        ///        &lt;UrlPattern&gt;&lt;![CDATA[https://.*?download\.nvidia\.com/nvapp/client/.*?/NVIDIA_app_.*?\.exe]]&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string AppsCatalog {
            get {
                return ResourceManager.GetString("AppsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.0.0.0 1oavsblobprodcus350.blob.core.windows.net
        ///0.0.0.0 2539951.r.bat.bing.com
        ///0.0.0.0 37bvsblobprodcus311.blob.core.windows.net
        ///0.0.0.0 a.ads1.msn.com
        ///0.0.0.0 a.ads2.msads.net
        ///0.0.0.0 a.ads2.msn.com
        ///0.0.0.0 a.rad.msn.com
        ///0.0.0.0 a-0001.a-msedge.net
        ///0.0.0.0 a-0001.dc-msedge.net
        ///0.0.0.0 a-0002.a-msedge.net
        ///0.0.0.0 a-0003.a-msedge.net
        ///0.0.0.0 a-0003.dc-msedge.net
        ///0.0.0.0 a-0004.a-msedge.net
        ///0.0.0.0 a-0005.a-msedge.net
        ///0.0.0.0 a-0006.a-msedge.net
        ///0.0.0.0 a-0007.a-msedge.net
        ///0.0.0.0 a-0008.a-m [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Blocklist {
            get {
                return ResourceManager.GetString("Blocklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DisablingWD {
            get {
                object obj = ResourceManager.GetObject("DisablingWD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NSudoLC {
            get {
                object obj = ResourceManager.GetObject("NSudoLC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Sound {
            get {
                return ResourceManager.GetStream("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Tickets&gt;
        ///	&lt;Ticket&gt;
        ///		&lt;product&gt;KMS&lt;/product&gt;
        ///		&lt;content&gt;
        ///			&lt;![CDATA[
        ///			&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;genuineAuthorization xmlns=&quot;http://www.microsoft.com/DRM/SL/GenuineAuthorization/1.0&quot;&gt;&lt;version&gt;1.0&lt;/version&gt;&lt;genuineProperties origin=&quot;sppclient&quot;&gt;&lt;properties&gt;OA3xOriginalProductId=;OA3xOriginalProductKey=;SessionId=TwBTAE0AYQBqAG8AcgBWAGUAcgBzAGkAbwBuAD0ANQA7AE8AUwBNAGkAbgBvAHIAVgBlAHIAcwBpAG8AbgA9ADEAOwBPAFMAUABsAGEAdABmAG8AcgBtAEkAZAA9ADIAOwBQAFAAPQAw [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] UltPower {
            get {
                object obj = ResourceManager.GetObject("UltPower", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
