name: Release Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore GTweak.sln

      - name: Build the solution (Release)
        run: msbuild GTweak.sln /t:Rebuild /p:Configuration=Release
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .Source/GTweak/bin/Release/
